TRANSLATE = {
    'NO_TYPE': 'осадков нет',
    'RAIN': 'дождь',
    'SLEET': 'снег с дождем',
    'SNOW': 'снег',
    'HAIL': 'град',
    'ZERO': None,
    'WEAK': 'слабый',
    'AVERAGE': 'средний',
    'STRONG': 'сильный',
    'VERY_STRONG': 'очень сильный',
    'CALM': 'спокойный',
    'NORTH': 'северный',
    'NORTH_EAST': 'северо-восточный',
    'EAST': 'восточный',
    'SOUTH_EAST': 'юго-восточный',
    'SOUTH': 'южный',
    'SOUTH_WEST': 'юго-западный',
    'WEST': 'западный',
    'NORTH_WEST': 'северо-западный',
    'CLEAR': 'ясно',
    'PARTLY': 'мало-облачно',
    'SIGNIFICANT': 'облачно с прояснениями',
    'CLOUDY': 'облачно',
    'OVERCAST': 'пасмурно',
}
